[workspace]

members = [
    "app",
    "ui",
    "utils",
    "services",
    "global",
    "pages/home",
    "pages/projects",
    "pages/not_found",
    "pages/home",
    "pages/links",
    "pages/post",
    "router",
]
